# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80b6ad58ac7c420b4b068390cf6703582e58dbe2109460483c143d27a3bc86f3082628e57ae9cb89189a5aa0ef7101685f8ef0e137f47a38df125349ec157f6b

test:
  secret_key_base: 5842f48779ccd0aeee57bf73a42630b9bc87904215ed88d8ad194652c8ce7d434ae1da757e47f5470528370800a86ab5dc310502e325841f7f79cd32747f6daf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
